[package]
name = "fxrs-terminal-host"
autobins = false
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
description = "Private detached terminal companion library for fxrs"
readme.workspace = true

[dependencies]
fx-core.workspace = true
fx-process.workspace = true
serde_json.workspace = true
